# Generated by Django 5.2.6 on 2025-10-08 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnePieceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'one_piece_set',
            },
        ),
        migrations.CreateModel(
            name='OnePieceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('foil_type', models.CharField(default='Normal', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tcgplayer_url', models.URLField(blank=True, null=True)),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rarity', models.CharField(blank=True, max_length=100, null=True)),
                ('card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('life', models.IntegerField(blank=True)),
                ('power', models.IntegerField(blank=True)),
                ('subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.IntegerField(blank=True)),
                ('counter', models.IntegerField(blank=True)),
                ('last_update', models.DateField()),
            ],
            options={
                'db_table': 'one_piece_card',
                'unique_together': {('product_id', 'foil_type')},
            },
        ),
        migrations.CreateModel(
            name='OnePieceCardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('history_date', models.DateField()),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'one_piece_card_history',
                'unique_together': {('card_id', 'history_date')},
            },
        ),
        migrations.CreateModel(
            name='OnePieceDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'one_piece_deck',
                'indexes': [models.Index(fields=['user'], name='ix_deck_user'), models.Index(fields=['leader'], name='ix_deck_leader')],
            },
        ),
        migrations.CreateModel(
            name='OnePieceDeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_foil', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='bounty_api.onepiececard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bounty_api.onepiecedeck')),
            ],
            options={
                'db_table': 'one_piece_deck_card',
                'unique_together': {('deck', 'card')},
            },
        ),
    ]
