# Generated by Django 5.2.6 on 2025-09-12 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnePieceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'one_piece_card_set',
            },
        ),
        migrations.CreateModel(
            name='OnePieceCard',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tcgplayer_url', models.URLField(blank=True, null=True)),
                ('market_price', models.FloatField(blank=True, null=True)),
                ('foil_type', models.CharField(default='Normal', max_length=50)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('life', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'one_piece_card',
                'indexes': [models.Index(fields=['card_id', 'foil_type'], name='ix_card_cardid_foil'), models.Index(fields=['color'], name='ix_card_color'), models.Index(fields=['card_type'], name='ix_card_card_type'), models.Index(fields=['cost'], name='ix_card_cost'), models.Index(fields=['power'], name='ix_card_power'), models.Index(fields=['counter'], name='ix_card_counter')],
            },
        ),
        migrations.CreateModel(
            name='OnePieceCardHistory',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tcgplayer_url', models.URLField(blank=True, null=True)),
                ('market_price', models.FloatField(blank=True, null=True)),
                ('foil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('life', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('history_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'one_piece_card_history',
                'indexes': [models.Index(fields=['id'], name='ix_card_history_id'), models.Index(fields=['card_id'], name='ix_card_history_card_id')],
            },
        ),
        migrations.CreateModel(
            name='OnePieceDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'one_piece_deck',
                'indexes': [models.Index(fields=['user'], name='ix_deck_user'), models.Index(fields=['leader'], name='ix_deck_leader')],
            },
        ),
        migrations.CreateModel(
            name='OnePieceDeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_foil', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='bounty_api.onepiececard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bounty_api.onepiecedeck')),
            ],
            options={
                'db_table': 'one_piece_deck_card',
                'unique_together': {('deck', 'card')},
            },
        ),
    ]
