# Generated by Django 5.2.6 on 2025-09-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onepiececard',
            table='one_piece_card',
        ),
        migrations.AlterModelTable(
            name='onepiececardhistory',
            table='one_piece_card_history',
        ),
        migrations.AlterModelTable(
            name='onepieceset',
            table='one_piece_set',
        ),
    ]
