# Generated by Django 5.2.6 on 2025-11-06 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='onepiecedeck',
            name='ix_deck_leader',
        ),
        migrations.AlterField(
            model_name='onepiecedeck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_piece_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
