# Generated by Django 5.2.6 on 2025-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_api', '0002_alter_onepiececard_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepiececard',
            name='last_update',
            field=models.DateField(),
        ),
    ]
