# Generated by Django 5.2.6 on 2025-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_api', '0003_alter_onepiececard_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepiececard',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='counter',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='life',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='power',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
